apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gsioajzyh-nodejs 
  janus-idp.io/tekton: gsioajzyh-nodejs
  backstage.io/kubernetes-id: gsioajzyh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gsioajzyh-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  